Complete task3
DeadDogDance/appointments-shedule-service pull request #3
Opened 2022-10-18 11:15 UTC by DeadDogDance

2022-10-19 05:16 UTC, foggy21 requested changes

2022-10-19 05:16 UTC, foggy21 commented on domain/Adaptors/IDoctorAdaptor.cs
> +        public Doctor? CreateDoctor(Doctor doctor);
Как ты создаешь доктора, передавая готового доктора?

2022-10-20 00:11 UTC, DeadDogDance commented on domain/Adaptors/IDoctorAdaptor.cs
> +        public Doctor? CreateDoctor(Doctor doctor);
Сейчас поправим

2022-10-21 08:01 UTC, Vixorem requested changes

2022-10-21 08:01 UTC, Vixorem commented on domain/Interactors/AppointmentInteractor.cs
> +        {
А если уже это время занято

2022-10-21 08:01 UTC, Vixorem commented on domain/Interactors/DoctorInteractor.cs
> +        public Result<bool> DeleteDoctor(int doctorId)
А если у него есть приемы, мож не надо тогда удалять

2022-10-21 08:03 UTC, DeadDogDance commented on domain/Adaptors/IAppointmentAdaptor.cs
> +    {
Посмотрел в статье, что репозиторий и адаптор означает одно и тоже

2022-10-23 09:37 UTC, Vixorem approved these changes

2022-10-25 00:03 UTC, merged